services:
    astina_social_links.twig.extension:
        class: Astina\Bundle\SocialLinksBundle\Twig\SocialLinksExtension
        arguments: [ '@fragment.handler' , '@request_stack']
        tags:
            - { name: twig.extension }
